# Site settings
title: ALICE SW Build Infrastructure pages
email: giulio.eulisse@cern.ch
description: > # this means to ignore newlines until "baseurl:"
  Initial documentation for ALICE new build infrastructure.
  This is work in progress.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://alisw.github.io" # the base hostname & protocol for your site
categories: [main, infrastructure]

# Build settings
markdown: kramdown
openstack_project: "ALICE Release Testing"
voc_name: "Giulio Eulisse"
experiment: "ALICE"
exp_prefix: "ali"
master_hostgroup: "alibuild/mesos/master"
slave_hostgroup: "alibuild/mesos/slave"
jenkins_hostgroup: "alibuild/jenkins"
frontend_hostgroup: "alibuild/frontend"
builduser: "alibuild"
openstack_image: "CC7 Base - x86_64 [2015-06-12]"
openstack_flavor: "hep2.24"
openstack_master_flavor: "hep2.4"
