# Site settings
title: ALICE SW Build Infrastructure pages
email: alice-analysis-operations@cern.ch
description: > # this means to ignore newlines until "baseurl:"
  Initial documentation for ALICE new build infrastructure.
  This is work in progress.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://alisw.github.io" # the base hostname & protocol for your site
categories: [main, infrastructure]

# Build settings
markdown: kramdown
highlighter: rouge
voc_name: "Giulio Eulisse"

menu_header: ALICE SW
menu:
  - name: ci
    label: CI
    items:
      - name: aliphysics-ci
        label: "AliPhysics"
  - name: git
    label: GIT
    items:
      - name: git-tutorial
        label: "Basic Tutorial"
      - name: git-advanced
        label: "Advanced Tutorial"
  - name: infrastructure
    label: Build Infrastructure
